### ISSUE TITLE
SS 3.2 version

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe-australia/silverstripe-sitemap#11]
Could you make a branch with a composer.json that is ready for 3.2? The current version wants definitely a 3.1 version...

**Comment by benjamintoddweb** [comment]
I would also appreciate this doing, or please advise if this module is being depreciated for SilverStripe v3.2 projects in favour of using https://github.com/Marketo/SilverStripe-Performable-Sitemaps

**Comment by nyeholt** [comment]
Have relaxed the constraint, it should now be ~3.1 which will allow compatibility with 3.2
